In [10]:
import numpy as np
import matplotlib.pyplot as plt

x_train = np.array([
        [26, 8],
        [26, 11],
        [29, 8],
        [34, 10],
        [36, 11],
        [33, 8],
        [30, 9],
        [27, 10],
        [27, 11],
        [26, 11],
        [31, 13],
        [34, 8]
        ])

y_train = ['go out', 'go out', 'go out', 'stay at home', 'stay at home', 'go out', 
        'go out','go out', 'go out', 'go out', 'stay at home', 'go out']

x_test1 = np.array([[30, 10]])
x_test2 = np.array([[28, 13]])
x_test3 = np.array([[29, 9]])
x_test4 = np.array([[31, 12]])
x_test5 = np.array([[27, 8]])

In [11]:
# calculate euclidean distance data testing 1

dis1 = np.sqrt(np.sum((x_train-x_test1)**2, axis=1))
dis1

array([4.47213595, 4.12310563, 2.23606798, 4.        , 6.08276253,
       3.60555128, 1.        , 3.        , 3.16227766, 4.12310563,
       3.16227766, 4.47213595])

In [16]:
nn_sort=dis1.argsort()[:5]
print(nn_sort)
nn_decision = np.take(y_train,nn_sort)
print(nn_decision)

from collections import Counter
b= Counter(np.take(y_train,dis1.argsort()[:5]))
b.most_common(1)[0][0]

[ 6  2  7  8 10]
['go out' 'go out' 'go out' 'go out' 'stay at home']


'go out'

In [12]:
# calculate euclidean distance data testing 2

dis2 = np.sqrt(np.sum((x_train-x_test2)**2, axis=1))
dis2

array([5.38516481, 2.82842712, 5.09901951, 6.70820393, 8.24621125,
       7.07106781, 4.47213595, 3.16227766, 2.23606798, 2.82842712,
       3.        , 7.81024968])

In [17]:
nn_sort=dis2.argsort()[:5]
print(nn_sort)
nn_decision = np.take(y_train,nn_sort)
print(nn_decision)

from collections import Counter
b= Counter(np.take(y_train,dis2.argsort()[:5]))
b.most_common(1)[0][0]

[ 8  1  9 10  7]
['go out' 'go out' 'go out' 'stay at home' 'go out']


'go out'

In [13]:
dis3 = np.sqrt(np.sum((x_train-x_test3)**2, axis=1))
dis3

array([3.16227766, 3.60555128, 1.        , 5.09901951, 7.28010989,
       4.12310563, 1.        , 2.23606798, 2.82842712, 3.60555128,
       4.47213595, 5.09901951])

In [18]:
nn_sort=dis3.argsort()[:5]
print(nn_sort)
nn_decision = np.take(y_train,nn_sort)
print(nn_decision)

from collections import Counter
b= Counter(np.take(y_train,dis3.argsort()[:5]))
b.most_common(1)[0][0]

[2 6 7 8 0]
['go out' 'go out' 'go out' 'go out' 'go out']


'go out'

In [14]:
dis4 = np.sqrt(np.sum((x_train-x_test4)**2, axis=1))
dis4

array([6.40312424, 5.09901951, 4.47213595, 3.60555128, 5.09901951,
       4.47213595, 3.16227766, 4.47213595, 4.12310563, 5.09901951,
       1.        , 5.        ])

In [24]:
nn_sort=dis4.argsort()[:5]
print(nn_sort)
nn_decision = np.take(y_train,nn_sort)
print(nn_decision)

from collections import Counter
b= Counter(np.take(y_train,dis4.argsort()[:5]))
b.most_common(1)[0][0]

[10  6  3  8  2]
['stay at home' 'go out' 'stay at home' 'go out' 'go out']


'go out'

In [15]:
dis5 = np.sqrt(np.sum((x_train-x_test5)**2, axis=1))
dis5

array([1.        , 3.16227766, 2.        , 7.28010989, 9.48683298,
       6.        , 3.16227766, 2.        , 3.        , 3.16227766,
       6.40312424, 7.        ])

In [20]:
nn_sort=dis5.argsort()[:5]
print(nn_sort)
nn_decision = np.take(y_train,nn_sort)
print(nn_decision)

from collections import Counter
b= Counter(np.take(y_train,dis5.argsort()[:5]))
b.most_common(1)[0][0]

[0 2 7 8 1]
['go out' 'go out' 'go out' 'go out' 'go out']


'go out'

In [23]:
from sklearn.preprocessing import LabelBinarizer
from sklearn.neighbors import KNeighborsClassifier

x_test = np.array([[30, 10],
                [28, 13],
                [29, 9],
                [31, 12],
                [27, 8]
                ])
y_test =['stay at home', 'go out', 'go out', 'stay at home', 'go out']

lb = LabelBinarizer()
y_trainbin = lb.fit_transform(y_train)
y_testbin = lb.transform(y_test)
print('label biner:%s' %y_testbin.T[0])

k = 5
clf = KNeighborsClassifier(n_neighbors=k)
clf.fit(x_train,y_trainbin.reshape(-1))
pred_bin = clf.predict(x_test)
pred_label = lb.inverse_transform(pred_bin)
print(pred_label)

label biner:[1 0 0 1 0]
['go out' 'go out' 'go out' 'go out' 'go out']


In [25]:
from sklearn.metrics import accuracy_score
print('akurasi: %s' % accuracy_score(y_testbin, pred_bin))

akurasi: 0.6


In [28]:
from sklearn.metrics import precision_score
print('presisi: %s' % precision_score(y_testbin, pred_bin))

presisi: 0.0


c:\Users\Asus\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [27]:
from sklearn.metrics import recall_score
print('recall: %s' % recall_score(y_testbin, pred_bin))

recall: 0.0
