In [3]:
import numpy as np
import matplotlib.pyplot as plt

x_train = np.array([
            [26, 8],
            [26, 11],
            [29, 8],
            [34, 10],
            [36, 11],
            [33, 8],
            [30, 9],
            [27, 10],
            [27, 11],
            [26, 11],
            [31, 13],
            [34, 8]
        ])

y_train = ['go out', 'go out', 'go out', 'stay at home', 'stay at home', 'go out', 
        'go out','go out', 'go out', 'go out', 'stay at home', 'go out']

x_test1 = np.array([[30, 10]])
x_test2 = np.array([[28, 13]])
x_test3 = np.array([[29, 9]])
x_test4 = np.array([[31, 12]])
x_test5 = np.array([[27, 8]])

In [4]:
from sklearn.preprocessing import LabelBinarizer
from sklearn.neighbors import KNeighborsClassifier

lb = LabelBinarizer()
y_trainbin = lb.fit_transform(y_train)
print(y_trainbin)

k = 5
clf = KNeighborsClassifier(n_neighbors=k)
clf.fit(x_train,y_trainbin.reshape(-1))
pred_bin = clf.predict(np.array([x_test1]).reshape(1,-1))[0]
pred_label = lb.inverse_transform(pred_bin)
print(pred_label)

[[0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]]
['go out']


In [5]:
from sklearn.preprocessing import LabelBinarizer
from sklearn.neighbors import KNeighborsClassifier

lb = LabelBinarizer()
y_trainbin = lb.fit_transform(y_train)
print(y_trainbin)

k = 5
clf = KNeighborsClassifier(n_neighbors=k)
clf.fit(x_train,y_trainbin.reshape(-1))
pred_bin = clf.predict(np.array([x_test2]).reshape(1,-1))[0]
pred_label = lb.inverse_transform(pred_bin)
print(pred_label)

[[0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]]
['go out']


In [6]:
from sklearn.preprocessing import LabelBinarizer
from sklearn.neighbors import KNeighborsClassifier

lb = LabelBinarizer()
y_trainbin = lb.fit_transform(y_train)
print(y_trainbin)

k = 5
clf = KNeighborsClassifier(n_neighbors=k)
clf.fit(x_train,y_trainbin.reshape(-1))
pred_bin = clf.predict(np.array([x_test3]).reshape(1,-1))[0]
pred_label = lb.inverse_transform(pred_bin)
print(pred_label)

[[0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]]
['go out']


In [7]:
from sklearn.preprocessing import LabelBinarizer
from sklearn.neighbors import KNeighborsClassifier

lb = LabelBinarizer()
y_trainbin = lb.fit_transform(y_train)
print(y_trainbin)

k = 5
clf = KNeighborsClassifier(n_neighbors=k)
clf.fit(x_train,y_trainbin.reshape(-1))
pred_bin = clf.predict(np.array([x_test4]).reshape(1,-1))[0]
pred_label = lb.inverse_transform(pred_bin)
print(pred_label)

[[0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]]
['go out']


In [8]:
from sklearn.preprocessing import LabelBinarizer
from sklearn.neighbors import KNeighborsClassifier

lb = LabelBinarizer()
y_trainbin = lb.fit_transform(y_train)
print(y_trainbin)

k = 5
clf = KNeighborsClassifier(n_neighbors=k)
clf.fit(x_train,y_trainbin.reshape(-1))
pred_bin = clf.predict(np.array([x_test5]).reshape(1,-1))[0]
pred_label = lb.inverse_transform(pred_bin)
print(pred_label)

[[0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]]
['go out']


In [9]:
from sklearn.preprocessing import LabelBinarizer
from sklearn.neighbors import KNeighborsClassifier

x_test = np.array([[30, 10],
                [28, 13],
                [29, 9],
                [31, 12],
                [27, 8]
                ])
y_test =['stay at home', 'go out', 'go out', 'stay at home', 'go out']

lb = LabelBinarizer()
y_trainbin = lb.fit_transform(y_train)
y_testbin = lb.transform(y_test)
print('label biner:%s' %y_testbin.T[0])

k = 5
clf = KNeighborsClassifier(n_neighbors=k)
clf.fit(x_train,y_trainbin.reshape(-1))
pred_bin = clf.predict(x_test)
pred_label = lb.inverse_transform(pred_bin)
print(pred_label)

label biner:[1 0 0 1 0]
['go out' 'go out' 'go out' 'go out' 'go out']


In [10]:
from sklearn.metrics import accuracy_score
print('akurasi: %s' % accuracy_score(y_testbin, pred_bin))

akurasi: 0.6


In [11]:
from sklearn.metrics import precision_score
print('presisi: %s' % precision_score(y_testbin, pred_bin))

presisi: 0.0


c:\Users\Asus\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [12]:
from sklearn.metrics import recall_score
print('recall: %s' % recall_score(y_testbin, pred_bin))

recall: 0.0
